name: polar_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # openapi_generator_annotations: ^6.1.0
  
  # path: ^1.8.0

dev_dependencies:
  # build_runner: ^2.4.14
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  lints: ^5.0.0
  # openapi_generator: ^6.1.0
  test: ^1.24.0
  
