import 'package:freezed_annotation/freezed_annotation.dart';

enum SubscriptionSortProperty {
  @JsonValue('customer')
  customer,
  @JsonValue('-customer')
  minus_customer,
  @JsonValue('status')
  status,
  @JsonValue('-status')
  minus_status,
  @JsonValue('started_at')
  started_at,
  @JsonValue('-started_at')
  minus_started_at,
  @JsonValue('current_period_end')
  current_period_end,
  @JsonValue('-current_period_end')
  minus_current_period_end,
  @JsonValue('ended_at')
  ended_at,
  @JsonValue('-ended_at')
  minus_ended_at,
  @JsonValue('ends_at')
  ends_at,
  @JsonValue('-ends_at')
  minus_ends_at,
  @JsonValue('amount')
  amount,
  @JsonValue('-amount')
  minus_amount,
  @JsonValue('product')
  product,
  @JsonValue('-product')
  minus_product,
  @JsonValue('discount')
  discount,
  @JsonValue('-discount')
  minus_discount,
}
