// ignore_for_file: constant_identifier_names

import 'package:freezed_annotation/freezed_annotation.dart';

enum WebhookEventType {
  @JsonValue('checkout.created')
  checkout_created,
  @JsonValue('checkout.updated')
  checkout_updated,
  @JsonValue('checkout.expired')
  checkout_expired,
  @JsonValue('customer.created')
  customer_created,
  @JsonValue('customer.updated')
  customer_updated,
  @JsonValue('customer.deleted')
  customer_deleted,
  @JsonValue('customer.state_changed')
  customer_state_changed,
  @JsonValue('customer_seat.assigned')
  customer_seat_assigned,
  @JsonValue('customer_seat.claimed')
  customer_seat_claimed,
  @JsonValue('customer_seat.revoked')
  customer_seat_revoked,
  @JsonValue('member.created')
  member_created,
  @JsonValue('member.updated')
  member_updated,
  @JsonValue('member.deleted')
  member_deleted,
  @JsonValue('order.created')
  order_created,
  @JsonValue('order.updated')
  order_updated,
  @JsonValue('order.paid')
  order_paid,
  @JsonValue('order.refunded')
  order_refunded,
  @JsonValue('subscription.created')
  subscription_created,
  @JsonValue('subscription.updated')
  subscription_updated,
  @JsonValue('subscription.active')
  subscription_active,
  @JsonValue('subscription.canceled')
  subscription_canceled,
  @JsonValue('subscription.uncanceled')
  subscription_uncanceled,
  @JsonValue('subscription.revoked')
  subscription_revoked,
  @JsonValue('subscription.past_due')
  subscription_past_due,
  @JsonValue('refund.created')
  refund_created,
  @JsonValue('refund.updated')
  refund_updated,
  @JsonValue('product.created')
  product_created,
  @JsonValue('product.updated')
  product_updated,
  @JsonValue('benefit.created')
  benefit_created,
  @JsonValue('benefit.updated')
  benefit_updated,
  @JsonValue('benefit_grant.created')
  benefit_grant_created,
  @JsonValue('benefit_grant.cycled')
  benefit_grant_cycled,
  @JsonValue('benefit_grant.updated')
  benefit_grant_updated,
  @JsonValue('benefit_grant.revoked')
  benefit_grant_revoked,
  @JsonValue('organization.updated')
  organization_updated,
}
